# -*- coding: utf-8 -*-
"""TallerOptimizacion16Abril.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17XzzkJS_U__m-50SUVgl9gwM93YkAr15
"""

#Punto 1

# Mezcla de fertilizantes

import numpy as np
from scipy.optimize import linprog

# Coeficientes de la función objetivo
# linprog MINIMIZA, así que ponemos negativos para maximizar
c = [-180, -220]

# Matriz de restricciones (lado izquierdo)
A = [
    [3, 4],   # Compuesto A
    [2, 1],   # Compuesto B
    [5, 3]    # Compuesto C
]

# Lado derecho
b = [120, 80, 150]

# Límites de variables (x1 >= 0, x2 >= 0)
bounds = [(0, None), (0, None)]

# Resolver
resultado = linprog(c, A_ub=A, b_ub=b, bounds=bounds, method='highs')

# Resultados
x1_opt, x2_opt = resultado.x
Z_opt = -resultado.fun

print(" = " * 45)
print("Mezcla de fertilizantes (PL)")
print(" = " * 45)

print(f"Estado: {'Óptimo encontrado' if resultado.success else 'Fallo'}")
print()
print(f"x1 (F1) = {x1_opt:.2f} ton")
print(f"x2 (F2) = {x2_opt:.2f} ton")
print(f"Ganancia máxima = ${Z_opt:.2f}")
print(" = " * 45)
